@startuml
!include diagram-config.puml!tutorial

actor "Customer" as customer
participant "Client\nApp" as partner
participant "Farfetch\nSTS" as farfetch
participant "/wishlists" as resource

group Access Token request
    customer -> partner: Clicks in login link
    partner -> farfetch: Requests Access Token to ""/authorize""\n""reponse_type=token"" <back:#e6e6e6>""id_token""</back>\n<back:#e6e6e6>+ ""openid"" scope</back>
    farfetch --> customer: ""302 Found"" redirect to authentication prompt
    customer -> farfetch: User authenticates with\nusername, password, and consent
    farfetch -> farfetch: Validates\nResource Owner\ncredentials
    farfetch --> partner: Access Token Response\n<back:#e6e6e6>+ ""id_token""</back>
end
group Protected resource access
    partner -> resource: Requests Resources (""Authorization: Bearer <access token>"")
    resource --> partner: Requested Resources
end
@enduml

