@startuml
!include diagram-config.puml!tutorial

participant "Client\nApp" as partner
participant "Farfetch\nSTS" as farfetch
participant "/bags" as resource

group Access Token request
    partner -> farfetch: Requests Access Token to ""/token""\n""grant_type=GuestUser""
    farfetch -> farfetch: Validates the client\ncredentials and\ngets guest user id
    farfetch --> partner: Access Token Response\nwith guest user id
end
group Protected resource access
    partner -> resource: Requests Resources (""Authorization: Bearer <access token>"")
    resource --> partner: Requested Resources
end
@enduml

