@startuml

'light-green: #94def3
'dark-green: #2c9ab7
'black: #222222
'background grey for actors and participants: #f8f8f8
'dark-grey: #e6e6e6

'### Color schema
!include diagram-config.puml!tutorial

scale 768 width
scale 1024 height


participant "Client\nApp" as partner
participant "Farfetch\nSTS" as farfetch
participant "/stocks" as resource

group Access Token request
    partner -> farfetch: curl --request POST \\\n    --url 'https://authbo.farfetch.net/connect/token' \\\n<i>    --header 'Content-Type: application/x-www-form-urlencoded'</i> \\\n<i>    --header 'accept: application/json'</i> \\\n<b>    --data 'grant_type=client_credentials'</b> \\\n<b>    --data 'client_id=farfetch_digitalAsset'</b> \\\n<b>    --data 'client_secret=secretProduction'</b> \\\n<b>    --data 'scope=stocks'</b> 
    farfetch -> farfetch: Validates\nthe client\ncredentials
    farfetch --> partner: HTTP/1.1 200 OK\n<i>Content-Type: application/json</i>\n<i>Cache-Control: no-store</i>\n<i>Pragma: no-cache</i>\n{\n  <b><back:#94def3>"access_token": "AYjcyMzY...3ZDhiNmJkNTY"</back></b>,\n  <b><back:#94def3>"token_type": "Bearer"</back></b>,\n  "expires_in": 2400\n}
end
group Protected resource access
    partner -> resource: curl --request GET \\\n  --url https://api.farfetch.net/stocks \\\n  <i>--header 'accept: application/json'</i> \\\n  <i>--header 'content-type: application/json'</i> \\\n  <i>--header</i> '<b><back:#94def3>authorization: Bearer AYjcyMzY3...ZDhiNmJkNTY</back></b>'
    resource --> partner: Requested Resources
end

left footer \n<color #000><font size=14><color #000><font size=14>\t\tFont and background color conventions:</font></color>\n<color #000><font size=14>\t\t - All fields are required</font></color>\n<color #000><font size=14>\t\t - <b>Required values</b></font></color>\n<color #000><font size=14>\t\t - <i>Headers</i></font></color>\n<color #000><font size=14>\t\t - <back:#94def3><b>Used in more than one message</b></back></font></color>

@enduml

